threadpool:threadpool.cpp
	g++ $^ -o $@ -lpthread -g    
pc_model1:pc_model1.cpp
	g++ $^ -o $@ -lpthread -g    
print:print.c
	gcc $^ -o $@ -lpthread  -g   -std=c99
pc_model:pc_model.cpp
	g++ $^ -o $@ -lpthread     
ticket:ticket.c
	gcc $^ -o $@ -lpthread     -std=c99
mycreate:mycreate.c
	gcc $^ -o $@ -lpthread	
